using System.Collections.Immutable;

namespace Ironbees.AgentMode.Models;

/// <summary>
/// Immutable state object for coding workflow.
/// Represents all information needed for workflow execution and recovery.
/// </summary>
public record CodingState
{
    /// <summary>
    /// Unique identifier for this workflow instance (UUID).
    /// Used for approval operations, state retrieval, and telemetry correlation.
    /// </summary>
    public required string StateId { get; init; }

    /// <summary>
    /// Original user request in natural language.
    /// Example: "Add JWT authentication to UserController"
    /// </summary>
    public required string UserRequest { get; init; }

    /// <summary>
    /// Structured specification parsed from user request.
    /// Generated by PlannerAgent, refined during workflow execution.
    /// </summary>
    public string? Spec { get; init; }

    /// <summary>
    /// Execution plan with step-by-step actions.
    /// Generated by PlannerAgent, approved by user in HITL mode.
    /// </summary>
    public ExecutionPlan? Plan { get; init; }

    /// <summary>
    /// List of file edits (diffs) to be applied.
    /// Generated by CoderAgent, validated by ValidatorAgent.
    /// </summary>
    public ImmutableList<FileEdit> CodeDiffs { get; init; } = ImmutableList<FileEdit>.Empty;

    /// <summary>
    /// Build result from MSBuild compilation.
    /// Used to detect compilation errors and guide refinement.
    /// </summary>
    public BuildResult? BuildResult { get; init; }

    /// <summary>
    /// Test result from dotnet test execution.
    /// Used to validate code correctness and guide refinement.
    /// </summary>
    public TestResult? TestResult { get; init; }

    /// <summary>
    /// Error context when workflow encounters failures.
    /// Contains error messages, stack traces, and diagnostic information.
    /// </summary>
    public string? ErrorContext { get; init; }

    /// <summary>
    /// Current iteration count in generate-validate-refine loop.
    /// Incremented after each validation failure.
    /// </summary>
    public int IterationCount { get; init; }

    /// <summary>
    /// Maximum iterations allowed before giving up.
    /// Default: 5
    /// </summary>
    public int MaxIterations { get; init; } = 5;

    /// <summary>
    /// Current node in the state graph (e.g., "PLAN", "CODE", "VALIDATE").
    /// Used by orchestrator to determine next agent to execute.
    /// </summary>
    public required string CurrentNode { get; init; }

    /// <summary>
    /// Timestamp of this state snapshot.
    /// </summary>
    public DateTime Timestamp { get; init; } = DateTime.UtcNow;

    /// <summary>
    /// Additional metadata for extensibility.
    /// Example: SolutionPath, TargetProject, UserPreferences, etc.
    /// </summary>
    public ImmutableDictionary<string, string> Metadata { get; init; }
        = ImmutableDictionary<string, string>.Empty;
}
